### ISSUE TITLE
Selecting network interface counters

### ISSUE THREAD

**Issue by GriffReborn** [CryptonZylog/carbonator#7] opened 2015-12-29 15:11 UTC
I would like to add performance counters for network interfaces, but it seems every server has a different NIC driver and NIC name.  So the performance counters are for all intents and purposes, uniquely named.  To my mind there are three ways forward

1) Wildcard feature.  Put in a "*" for instance, and it iterates through them all
2) Some way of detecting the active NIC and using that instance
3) As above, but checking for a NIC which is domain joined and using that instance

I found some useful code at the end of this post, it feels like it could be useful for this but it's a bit beyond my newbie C# kills to implement.

http://stackoverflow.com/questions/8657470/how-to-know-the-network-bandwidth-used-at-a-given-time#8666726

**Comment by CryptonZylog** [comment] 2015-12-29 22:10
1. This should be doable
2. Might be a bit much complexity here. Carbonator would still report metrics, for example, the bytes in/out would just be ``0``.
3. Seems like it may be much for carbonator again, but perhaps you can adjust that in your metric path to suit your needs.


Something to keep in mind: carbonator is designed to be agnostic to whatever performance counters you intend to use with it. It serves more like 'glue logic' between Windows Performance Counters and Carbon/Graphite; so I aim to keep it as simple as that ;-)

**Comment by GriffReborn** [comment] 2016-02-16 10:05
1. works for me, and fits in with issue #5

**Comment by CryptonZylog** [comment] 2016-03-03 21:26
Closed as duplicate of #5

**Closed by CryptonZylog** 2016-03-03 21:26 UTC
Labels: duplicate, enhancement
